#  development Dockerfile
# to build the docker image, call :
# docker build -f Dockerfile.dev -t my_project/-dev:0.0.1 .
# docker run -p 8000:8000 --name -dev my_project/-dev:0.0.1 
# see also https://snyk.io/blog/best-practices-containerizing-python-docker/

# to get the digest (=sha fingerprint) run:
# docker images --digests | grep python

# consider to create a django_build_image_base, store it in the registry and build from there, if caching is not working 
ARG PYTHON_VERSION=3.13

FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-bookworm  AS build_image
# to minimize image size one could build like (https://mherman.org/presentations/dockercon-2018/#39):
# using wheels

# set Docker Metadata
LABEL maintainer="mark doerr <mark.doerr@uni-greifswald.de>"
# or $VERSION
LABEL version="0.0.0"   
LABEL description=" - A qualitative analysis submission system for students in chemistry. (build image)"


ENV LANG=C.UTF-8\
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1\
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=${PYTHON_VERSION} \
    UV_PROJECT_ENVIRONMENT=/app/.venv \
    DEBIAN_FRONTEND=noninteractive \
    PROJECT_ROOT=/opt/

# Debian package caching
ARG APT_PROXY
RUN set -x \
    && if [ "${APT_PROXY}" ]; \
    then echo "Acquire::http { Proxy \"http://${APT_PROXY}\"; };" > /etc/apt/apt.conf.d/01proxy \
    ; fi

# build environment
RUN apt-get update \
    && apt-get install -y --no-install-recommends git build-essential gcc 

# activating the virtual environment
ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"   

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev
