# Generated by Django 6.0.8 on 2026-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type name, e.g. 'Analysis 3'.", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis type',
                'verbose_name_plural': 'Analysis types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.PositiveSmallIntegerField(default=1, help_text='1-based ordinal of this submission for the instance.')),
                ('idempotency_key', models.CharField(help_text='Client-generated key preventing duplicate submissions.', max_length=128)),
                ('score', models.PositiveIntegerField(default=0, help_text='Score awarded for this submission.')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Number of correctly selected ions.')),
                ('wrong_count', models.PositiveIntegerField(default=0, help_text='Number of wrongly selected ions (false positives).')),
                ('missing_count', models.PositiveIntegerField(default=0, help_text='Number of correct ions the student missed.')),
                ('penalty', models.PositiveIntegerField(default=0, help_text='Penalty applied for using a retry submission.')),
                ('ideal_score', models.PositiveIntegerField(default=0, help_text='Ideal score for the analysis at submission time.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of the submission.')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(help_text='Earliest time a submission is accepted (inclusive).')),
                ('window_end', models.DateTimeField(help_text='Latest time a submission is accepted (inclusive).')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Announcement number within the course (e.g. 3 for the 3rd analysis).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_ions', models.ManyToManyField(blank=True, help_text='Ions actually present in this concrete analysis (the answer key).', related_name='instances', to='substances.ion')),
            ],
            options={
                'verbose_name': 'Analysis instance',
                'verbose_name_plural': 'Analysis instances',
                'ordering': ['number', 'window_start'],
            },
        ),
    ]
