# Generated by Django 6.0.8 on 2026-09-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('config', '0001_initial'),
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinstance',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this instance belongs to (used by assistants).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_instances', to='config.course'),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='possible_ions',
            field=models.ManyToManyField(blank=True, help_text='Ions that *can* occur in this analysis type (shown to students).', related_name='analysis_types', to='substances.ion'),
        ),
        migrations.AddField(
            model_name='analysisinstance',
            name='type',
            field=models.ForeignKey(help_text='Analysis type (defines the possible ion set).', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='analyses.analysistype'),
        ),
        migrations.AddField(
            model_name='submission',
            name='analysis_instance',
            field=models.ForeignKey(help_text='Analysis instance this submission belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='analyses.analysisinstance'),
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_ions',
            field=models.ManyToManyField(blank=True, help_text='Ions the student selected.', related_name='submissions', to='substances.ion'),
        ),
    ]
