# Generated by Django 6.1.1 on 2026-10-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinstance',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this instance belongs to (used by assistants).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_instances', to='config.course'),
        ),
        migrations.AddField(
            model_name='analysisnotification',
            name='course',
            field=models.ForeignKey(help_text='Course the re-trial belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_notifications', to='config.course'),
        ),
        migrations.AddField(
            model_name='analysisnotification',
            name='instance',
            field=models.ForeignKey(help_text='The newly generated (re-trial) analysis instance.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analyses.analysisinstance'),
        ),
    ]
