# Generated by Django 6.1.1 on 2026-10-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0002_initial'),
        ('substances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisnotification',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Assistants who have acknowledged this notification.', related_name='read_analysis_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisnotification',
            name='student',
            field=models.ForeignKey(help_text='Student whose wrong submission triggered the re-trial.', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_analysis_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='possible_ions',
            field=models.ManyToManyField(blank=True, help_text='Ions that *can* occur in this analysis type (shown to students).', related_name='analysis_types', to='substances.ion'),
        ),
        migrations.AddField(
            model_name='analysisinstance',
            name='type',
            field=models.ForeignKey(help_text='Analysis type (defines the possible ion set).', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='analyses.analysistype'),
        ),
        migrations.AddField(
            model_name='submission',
            name='analysis_instance',
            field=models.ForeignKey(help_text='Analysis instance this submission belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='analyses.analysisinstance'),
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_ions',
            field=models.ManyToManyField(blank=True, help_text='Ions the student selected.', related_name='submissions', to='substances.ion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(help_text='Student who made this submission.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('analysis_instance', 'student', 'idempotency_key'), name='unique_idempotency_per_student_instance'),
        ),
    ]
