# Generated by Django 6.1.1 on 2026-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_initial'),
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinstance',
            name='assigned_substances',
            field=models.ManyToManyField(blank=True, help_text='Substances randomly assigned to this student for the analysis (the salts to prepare / reference), recorded when the answer key is randomized.', related_name='instances', to='substances.substance'),
        ),
    ]
