# Generated by Django 6.1.1 on 2026-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinstance',
            name='label',
            field=models.CharField(blank=True, default='', help_text="Short per-student label shown to users, e.g. 'Cations1_1' (type name without spaces plus the student's labspace id). Set when the instance is created for a specific student.", max_length=128),
        ),
    ]
