# Generated by Django 6.1.1 on 2026-10-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_analysisinstance_assigned_substances'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistype',
            name='default_window_end',
            field=models.DateTimeField(blank=True, help_text='Default latest time a submission is accepted (inherited by new sessions).', null=True),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='default_window_start',
            field=models.DateTimeField(blank=True, help_text='Default earliest time a submission is accepted (inherited by new sessions).', null=True),
        ),
    ]
