# Generated by Django 6.1.1 on 2026-10-04 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_analysistype_default_window_end_and_more'),
        ('config', '0009_gradingconfig_retry_point_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistype',
            name='max_repetitions',
            field=models.PositiveSmallIntegerField(default=2, help_text="In 'new analysis' submission mode: maximum number of re-trial analyses generated per student and announcement after a wrong submission."),
        ),
        migrations.CreateModel(
            name='AnalysisNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course the re-trial belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_notifications', to='config.course')),
                ('instance', models.ForeignKey(help_text='The newly generated (re-trial) analysis instance.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analyses.analysisinstance')),
                ('read_by', models.ManyToManyField(blank=True, help_text='Assistants who have acknowledged this notification.', related_name='read_analysis_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student whose wrong submission triggered the re-trial.', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_analysis_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis notification',
                'verbose_name_plural': 'Analysis notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
