# Generated by Django 6.0.8 on 2026-09-08 18:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Login attempt',
                'verbose_name_plural': 'Login attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('admin', 'Admin')], default='student', help_text='Role of the user in the system.', max_length=16)),
                ('matriculation_no', models.CharField(blank=True, default='', help_text='Matriculation number (students only).', max_length=64)),
                ('lab', models.CharField(blank=True, default='', help_text="Assigned lab / lab course (e.g. 'Inorganic Chemistry, Biology track').", max_length=255)),
                ('labspace_id', models.CharField(blank=True, default='', help_text='Labspace identification (institutional user id).', max_length=64)),
                ('token_version', models.PositiveIntegerField(default=0, help_text='Bumped on logout to revoke all issued JWTs.')),
                ('course', models.ForeignKey(blank=True, help_text='Course the student is enrolled in (students only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='config.course')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Announcement number of this analysis within the course (e.g. 3 for the 3rd analysis).')),
                ('course', models.ForeignKey(help_text='Course this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='config.course')),
                ('instance', models.ForeignKey(help_text='Analysis instance (sheet) assigned to the student.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='analyses.analysisinstance')),
                ('student', models.ForeignKey(help_text='Student the analysis is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student analysis assignment',
                'verbose_name_plural': 'Student analysis assignments',
                'constraints': [models.UniqueConstraint(fields=('student', 'instance'), name='unique_student_instance_assignment'), models.UniqueConstraint(fields=('course', 'student', 'number'), name='unique_course_student_number')],
            },
        ),
        migrations.CreateModel(
            name='StudentBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Barcode payload, e.g. 'FC-<student_id>-<uuid8>'.", max_length=128, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive barcodes cannot be used to log in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='Student this barcode belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student barcode',
                'verbose_name_plural': 'Student barcodes',
                'constraints': [models.UniqueConstraint(fields=('value',), name='unique_barcode_value')],
            },
        ),
    ]
