# Generated by Django 6.1.1 on 2026-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='Telephone / mobile number (e.g. for practical contact).', max_length=64),
        ),
    ]
