# Generated by Django 6.1.1 on 2026-10-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=True, help_text='Whether the user has completed onboarding. OAuth-created students start False and complete an onboarding page (course + metadata + generated analyses); manually created and self-registered accounts are onboarded by default.'),
        ),
    ]
