# Generated by Django 6.1.1 on 2026-10-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentassignment',
            name='unique_course_student_number',
        ),
    ]
