# Generated by Django 6.1.1 on 2026-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studentassignment_unique_course_student_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='onboarded',
            new_name='registered',
        ),
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Whether the user has completed registration. OAuth-created students start '
                    'False and complete a registration page (course + metadata + generated analyses); '
                    'manually created and self-registered accounts are registered by default.'
                ),
            ),
        ),
    ]
