# Generated by Django 6.1.1 on 2026-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(choices=[('manual', 'Manual (created by an admin in Admin → Courses → Members)'), ('self_registration', 'Self-registration (students register + confirm their e-mail)'), ('oauth', 'OAuth (students sign in via an external identity provider)')], default='manual', help_text='How new student accounts are created. Exactly one mode is active at a time: manual (admin creates accounts), self-registration (students register and confirm their e-mail) or OAuth (students sign in via an external provider and complete a registration page).', max_length=24)),
                ('points_per_analysis', models.PositiveSmallIntegerField(default=10, help_text='Points per correctly identified analysis (per-analysis mode).')),
                ('analyses_per_course', models.PositiveSmallIntegerField(default=3, help_text='Number of analyses (announcements) per student per course.')),
                ('backup_enabled', models.BooleanField(default=False, help_text='Run a scheduled database backup (in-process scheduler).')),
                ('backup_interval_minutes', models.PositiveIntegerField(default=60, help_text='Minutes between scheduled backups (minimum 1).')),
                ('backup_location', models.CharField(blank=True, default='backups', help_text="Directory for backup files. Relative paths are resolved against the project root (e.g. 'backups' or '/var/backups/flamecheck').", max_length=500)),
                ('backup_keep', models.PositiveIntegerField(default=10, help_text='Number of backups to keep; older ones are deleted after each backup.')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_backup_file', models.CharField(blank=True, default='', max_length=255)),
                ('last_restore_at', models.DateTimeField(blank=True, null=True)),
                ('last_restore_file', models.CharField(blank=True, default='', max_length=255)),
                ('login_logo', models.FileField(blank=True, help_text='Optional university/institut logo (SVG or PNG) shown on the login page.', null=True, upload_to='branding')),
                ('login_qr', models.FileField(blank=True, help_text='Optional QR code (SVG or PNG) of the login URL, shown on wide screens.', null=True, upload_to='branding')),
            ],
            options={
                'verbose_name': 'Application settings',
                'verbose_name_plural': 'Application settings',
            },
        ),
        migrations.CreateModel(
            name='AssistantCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Assistant course assignment',
                'verbose_name_plural': 'Assistant course assignments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name (unique).', max_length=255, unique=True)),
                ('semester', models.CharField(blank=True, default='', help_text="Semester label (e.g. 'WS 2026').", max_length=64)),
                ('track', models.CharField(blank=True, default='', help_text='Specialisation track (biology, pharmacy, materials science, ...).', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Only active courses are offered to students.')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_correct_ion', models.PositiveSmallIntegerField(default=10, help_text='Points per correctly identified ion in per-ion mode; points per completed analysis (all ions exact) in per-analysis mode.')),
                ('passing_score', models.PositiveIntegerField(default=50, help_text='Minimum total points a student needs across all analyses of the course to pass it (0 disables the pass check).')),
                ('penalty_second_submission', models.PositiveSmallIntegerField(default=2, help_text='Points deducted when the 2nd submission corrects a miss (per-ion mode).')),
                ('penalty_third_submission', models.PositiveSmallIntegerField(default=4, help_text='Points deducted when the 3rd submission corrects a miss (per-ion mode).')),
                ('false_positive_deduction', models.PositiveSmallIntegerField(default=0, help_text='Points deducted per wrongly selected ion (0 disables).')),
                ('retry_point_deduction', models.PositiveSmallIntegerField(default=0, help_text="'New analysis' mode: points subtracted from the course total for each earlier (superseded) re-trial attempt (0 disables the penalty).")),
                ('grading_mode', models.CharField(choices=[('per_ion', 'Per ion (default)'), ('per_analysis', 'Per analysis (all-or-nothing)')], default='per_ion', help_text='Scoring mode: award points per correct ion, or only if the whole set is exact.', max_length=16)),
                ('submission_mode', models.CharField(choices=[('resubmit', 'Resubmit (default)'), ('new_analysis', 'New analysis on wrong submission')], default='resubmit', help_text="How a wrong submission is handled: allow resubmissions on the same analysis, or hand out a fresh random analysis of the same type (up to the type's max repetitions).", max_length=16)),
                ('max_submissions_per_analysis', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of submissions allowed per analysis instance.')),
                ('final_score_strategy', models.CharField(choices=[('best', 'Best submission'), ('last', 'Last submission')], default='best', help_text='How the final score is derived when multiple submissions exist.', max_length=8)),
            ],
            options={
                'verbose_name': 'Grading configuration',
                'verbose_name_plural': 'Grading configurations',
            },
        ),
    ]
