# Generated by Django 6.0.8 on 2026-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_analysis', models.PositiveSmallIntegerField(default=10, help_text='Points per correctly identified analysis (per-analysis mode).')),
                ('analyses_per_course', models.PositiveSmallIntegerField(default=3, help_text='Number of analyses (announcements) per student per course.')),
            ],
            options={
                'verbose_name': 'Application settings',
                'verbose_name_plural': 'Application settings',
            },
        ),
        migrations.CreateModel(
            name='AssistantCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Assistant course assignment',
                'verbose_name_plural': 'Assistant course assignments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name (unique).', max_length=255, unique=True)),
                ('semester', models.CharField(blank=True, default='', help_text="Semester label (e.g. 'WS 2026').", max_length=64)),
                ('track', models.CharField(blank=True, default='', help_text='Specialisation track (biology, pharmacy, materials science, ...).', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Only active courses are offered to students.')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_correct_ion', models.PositiveSmallIntegerField(default=10, help_text='Points awarded per correctly identified ion (per-ion mode).')),
                ('penalty_second_submission', models.PositiveSmallIntegerField(default=2, help_text='Points deducted when the 2nd submission corrects a miss (per-ion mode).')),
                ('penalty_third_submission', models.PositiveSmallIntegerField(default=4, help_text='Points deducted when the 3rd submission corrects a miss (per-ion mode).')),
                ('false_positive_deduction', models.PositiveSmallIntegerField(default=0, help_text='Points deducted per wrongly selected ion (0 disables).')),
                ('grading_mode', models.CharField(choices=[('per_ion', 'Per ion (default)'), ('per_analysis', 'Per analysis (all-or-nothing)')], default='per_ion', help_text='Scoring mode: award points per correct ion, or only if the whole set is exact.', max_length=16)),
                ('max_submissions_per_analysis', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of submissions allowed per analysis instance.')),
                ('final_score_strategy', models.CharField(choices=[('best', 'Best submission'), ('last', 'Last submission')], default='best', help_text='How the final score is derived when multiple submissions exist.', max_length=8)),
            ],
            options={
                'verbose_name': 'Grading configuration',
                'verbose_name_plural': 'Grading configurations',
            },
        ),
    ]
