# Generated by Django 6.1.1 on 2026-10-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantcourse',
            name='assistant',
            field=models.ForeignKey(help_text='Assistant responsible for this course.', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantcourse',
            name='course',
            field=models.ForeignKey(help_text='Course the assistant supports.', on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='config.course'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='active_course',
            field=models.ForeignKey(blank=True, help_text='Currently active course (the one students see after login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plus_active_settings', to='config.course'),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this grading configuration belongs to. Null is the global default used by any course without its own configuration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_configs', to='config.course'),
        ),
        migrations.AddConstraint(
            model_name='assistantcourse',
            constraint=models.UniqueConstraint(fields=('assistant', 'course'), name='unique_assistant_course'),
        ),
        migrations.AddConstraint(
            model_name='gradingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course',), name='unique_grading_config_per_course'),
        ),
    ]
