# Generated by Django 6.0.8 on 2026-09-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantcourse',
            name='assistant',
            field=models.ForeignKey(help_text='Assistant responsible for this course.', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantcourse',
            name='course',
            field=models.ForeignKey(help_text='Course the assistant supports.', on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='config.course'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='active_course',
            field=models.ForeignKey(blank=True, help_text='Currently active course (the one students see after login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plus_active_settings', to='config.course'),
        ),
        migrations.AddConstraint(
            model_name='assistantcourse',
            constraint=models.UniqueConstraint(fields=('assistant', 'course'), name='unique_assistant_course'),
        ),
    ]
