# Generated by Django 6.1.1 on 2026-10-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this grading configuration belongs to. Null is the global default used by any course without its own configuration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_configs', to='config.course'),
        ),
        migrations.AddConstraint(
            model_name='gradingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course',), name='unique_grading_config_per_course'),
        ),
    ]
