# Generated by Django 6.1.1 on 2026-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='mc_penalty_per_wrong',
            field=models.PositiveSmallIntegerField(default=2, help_text='Multiple choice: points deducted for each wrongly answered question on a card.'),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='mc_points_per_card',
            field=models.PositiveSmallIntegerField(default=10, help_text='Multiple choice: points awarded per card when every question is answered correctly.'),
        ),
    ]
