# Generated by Django 6.1.1 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_gradingconfig_mc_penalty_per_wrong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='notify_assistant_on_submission',
            field=models.BooleanField(default=False, help_text="Send the course's assistants a PGP-encrypted e-mail for every student submission (Admin → Settings → Notifications)."),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pgp_private_key',
            field=models.TextField(blank=True, default='', help_text='Armored (-----BEGIN PGP PRIVATE KEY BLOCK-----) private key used to SIGN outgoing e-mails.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pgp_private_key_passphrase',
            field=models.CharField(blank=True, default='', help_text='Passphrase protecting the signing private key (empty = unprotected).', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pgp_public_key',
            field=models.TextField(blank=True, default='', help_text="Armored (-----BEGIN PGP PUBLIC KEY BLOCK-----) public key used to ENCRYPT outgoing e-mails (the recipient's key)."),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='', help_text='The From: address of sent e-mails.', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='SMTP server hostname.', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='SMTP password / app password.', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=587, help_text='SMTP server port (587 for STARTTLS, 465 for SSL).'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_security',
            field=models.CharField(choices=[('none', 'None (plain, port 25)'), ('tls', 'STARTTLS (port 587)'), ('ssl', 'Implicit SSL/TLS (port 465)')], default='tls', help_text='How the SMTP connection is secured.', max_length=8),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='SMTP username (empty = anonymous).', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='notify_student_on_submission',
            field=models.BooleanField(default=False, help_text='Send the student a PGP-encrypted e-mail confirmation for every submission in this course (Admin → Courses).'),
        ),
    ]
