# Generated by Django 6.1.1 on 2026-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_gradingconfig_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Minimum total points a student needs across all analyses of the course to pass it (0 disables the pass check).'),
        ),
        migrations.AlterField(
            model_name='gradingconfig',
            name='points_per_correct_ion',
            field=models.PositiveSmallIntegerField(default=10, help_text='Points per correctly identified ion in per-ion mode; points per completed analysis (all ions exact) in per-analysis mode.'),
        ),
    ]
