# Generated by Django 6.1.1 on 2026-10-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_gradingconfig_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='backup_enabled',
            field=models.BooleanField(default=False, help_text='Run a scheduled database backup (in-process scheduler).'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='backup_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes between scheduled backups (minimum 1).'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='backup_keep',
            field=models.PositiveIntegerField(default=10, help_text='Number of backups to keep; older ones are deleted after each backup.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='backup_location',
            field=models.CharField(blank=True, default='backups', help_text="Directory for backup files. Relative paths are resolved against the project root (e.g. 'backups' or '/var/backups/flamecheck').", max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_backup_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_restore_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_restore_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
