# Generated by Django 6.1.1 on 2026-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_appsettings_backup_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='login_logo',
            field=models.FileField(blank=True, help_text='Optional university/institut logo (SVG) shown on the login page.', null=True, upload_to='branding'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='login_qr',
            field=models.FileField(blank=True, help_text='Optional QR code (SVG or PNG) of the login URL, shown on wide screens.', null=True, upload_to='branding'),
        ),
    ]
