# Generated by Django 6.1.1 on 2026-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_appsettings_login_logo_appsettings_login_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='login_logo',
            field=models.FileField(blank=True, help_text='Optional university/institut logo (SVG or PNG) shown on the login page.', null=True, upload_to='branding'),
        ),
    ]
