# Generated by Django 6.1.1 on 2026-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_appsettings_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='retry_point_deduction',
            field=models.PositiveSmallIntegerField(default=0, help_text="'New analysis' mode: points subtracted from the course total for each earlier (superseded) re-trial attempt (0 disables the penalty)."),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='submission_mode',
            field=models.CharField(choices=[('resubmit', 'Resubmit (default)'), ('new_analysis', 'New analysis on wrong submission')], default='resubmit', help_text="How a wrong submission is handled: allow resubmissions on the same analysis, or hand out a fresh random analysis of the same type (up to the type's max repetitions).", max_length=16),
        ),
    ]
