# Generated by Django 6.1.1 on 2026-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_gradingconfig_retry_point_deduction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='onboarding',
            new_name='registration',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='registration',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual (created by an admin in Admin → Courses → Members)'),
                    ('self_registration', 'Self-registration (students register + confirm their e-mail)'),
                    ('oauth', 'OAuth (students sign in via an external identity provider)'),
                ],
                default='manual',
                help_text=(
                    'How new student accounts are created. Exactly one mode is active at a time: '
                    'manual (admin creates accounts), self-registration (students register and confirm '
                    'their e-mail) or OAuth (students sign in via an external provider and complete a '
                    'registration page).'
                ),
                max_length=24,
            ),
        ),
    ]
