# Generated by Django 6.1.1 on 2026-10-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0003_gradingconfig_mc_penalty_per_wrong_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title shown on the student's card.", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Documentation (admin only): what the card covers.')),
                ('remarks', models.TextField(blank=True, default='', help_text='Documentation (admin only): free remarks about the card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mc_cards', to='config.course')),
            ],
            options={
                'verbose_name': 'Multiple-choice card',
                'verbose_name_plural': 'Multiple-choice cards',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The question statement shown to students.', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Documentation (admin only): what the question covers, source, learning objective.')),
                ('remarks', models.TextField(blank=True, default='', help_text='Documentation (admin only): free remarks, e.g. grading notes or lab context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mc_questions', to='config.course')),
            ],
            options={
                'verbose_name': 'Multiple-choice question',
                'verbose_name_plural': 'Multiple-choice questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MCSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(help_text='Earliest time a submission is accepted (inclusive).')),
                ('window_end', models.DateTimeField(help_text='Latest time a submission is accepted (inclusive).')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Announcement number within the course (e.g. 1 for the 1st card).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(help_text='Card this sheet presents.', on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='multichoice.mccard')),
                ('course', models.ForeignKey(blank=True, help_text='Course this sheet belongs to (used for per-course grading).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mc_sheets', to='config.course')),
            ],
            options={
                'verbose_name': 'Multiple-choice sheet',
                'verbose_name_plural': 'Multiple-choice sheets',
                'ordering': ['number', 'window_start'],
            },
        ),
        migrations.CreateModel(
            name='MCOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text shown to students.', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this option is the correct answer (exactly one per question).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order of the option within the question.')),
                ('question', models.ForeignKey(help_text='Question this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='multichoice.mcquestion')),
            ],
            options={
                'verbose_name': 'Multiple-choice option',
                'verbose_name_plural': 'Multiple-choice options',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('question', 'sort_order'), name='unique_option_order_per_question')],
            },
        ),
        migrations.CreateModel(
            name='MCCardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position of the question on the card.')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_questions', to='multichoice.mccard')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_links', to='multichoice.mcquestion')),
            ],
            options={
                'verbose_name': 'Card question link',
                'verbose_name_plural': 'Card question links',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('card', 'question'), name='unique_question_per_card')],
            },
        ),
        migrations.CreateModel(
            name='MCStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Announcement number within the course.')),
                ('course', models.ForeignKey(help_text='Course this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mc_assignments', to='config.course')),
                ('sheet', models.ForeignKey(help_text='Sheet (card presentation) assigned to the student.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='multichoice.mcsheet')),
                ('student', models.ForeignKey(help_text='Student the card is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='mc_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student multiple-choice assignment',
                'verbose_name_plural': 'Student multiple-choice assignments',
                'constraints': [models.UniqueConstraint(fields=('student', 'sheet'), name='unique_student_sheet_assignment')],
            },
        ),
        migrations.CreateModel(
            name='MCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Mapping of question id to selected option id.')),
                ('submission_number', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('ideal_score', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(help_text='Sheet this submission answers.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='multichoice.mcsheet')),
                ('student', models.ForeignKey(help_text='Student who made this submission.', on_delete=django.db.models.deletion.PROTECT, related_name='mc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multiple-choice submission',
                'verbose_name_plural': 'Multiple-choice submissions',
                'ordering': ['submitted_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'student', 'idempotency_key'), name='unique_mc_idempotency_per_student_sheet')],
            },
        ),
    ]
