# Generated by Django 6.1.1 on 2026-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text="Canonical ion symbol: formula then sign then magnitude, e.g. 'NH4+1' or 'SO4-2'.", max_length=32)),
                ('name', models.CharField(help_text="Human readable name, e.g. 'Ammonium'.", max_length=255)),
                ('charge', models.IntegerField(default=0, help_text='Ionic charge (e.g. +2, -1, -2, -3).')),
                ('kind', models.CharField(choices=[('cation', 'Cation'), ('anion', 'Anion')], help_text='Cation or anion.', max_length=8)),
                ('group', models.CharField(blank=True, default='', help_text="Systematic group, e.g. 'Group I', 'Group III', or free text.", max_length=64)),
            ],
            options={
                'verbose_name': 'Ion',
                'verbose_name_plural': 'Ions',
                'ordering': ['kind', 'group', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'kind'), name='unique_symbol_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name, e.g. 'Sodium chloride'.", max_length=255)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='List of synonyms / alternative names.')),
                ('formula', models.CharField(blank=True, default='', help_text="Chemical formula, e.g. 'NaCl'.", max_length=128)),
                ('pubchem_id', models.CharField(blank=True, default='', help_text='PubChem CID, if known.', max_length=32)),
                ('wikipedia_link', models.URLField(blank=True, default='', help_text='Link to a Wikipedia article, if any.')),
                ('ions', models.ManyToManyField(blank=True, help_text='Ions this substance provides in aqueous solution.', related_name='substances', to='substances.ion')),
            ],
            options={
                'verbose_name': 'Substance',
                'verbose_name_plural': 'Substances',
                'ordering': ['name'],
            },
        ),
    ]
